# Generated by Django 4.1.7 on 2023-02-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.CharField(choices=[('USA', 'United States'), ('AUS', 'Australia')], default='USA', max_length=15, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
